/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FeaturedCarousel: typeof import('./src/components/FeaturedCarousel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    LatestPosts: typeof import('./src/components/LatestPosts.vue')['default']
    LinksSection: typeof import('./src/components/LinksSection.vue')['default']
    MediaSection: typeof import('./src/components/MediaSection.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectShowcase: typeof import('./src/components/ProjectShowcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolsSection: typeof import('./src/components/ToolsSection.vue')['default']
  }
}
